<%--
  Created by IntelliJ IDEA.
  User: jthota
  Date: 8/12/2024
  Time: 10:45 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="container">

    <div class="btn-group" role="group" aria-label="Basic example" style="margin-left:80%">
        <button id="expandAll" type="button" class="btn btn-secondary" onclick=expandAll()>Expand All</button>
        <button id="collapseAll" type="button" class="btn btn-secondary" onclick=collapseAll() >Collapse</button>

    </div><br>
    <script>
        $(function () {
            $('#collapseAll').hide()
        })
        function expandAll(){
            $('#accordion .collapse').addClass("show");
            $('#expandAll').hide()
            $('#collapseAll').show()
        }
        function collapseAll(){
            $('#accordion .collapse').removeClass("show");
            $('#expandAll').show()
            $('#collapseAll').hide()
        }
    </script>
<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    1. What is the ToolKit?
                </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                The SCGE ToolKit is a repository that collects and disseminates, by way of this website, experimental data generated by SCGE-funded laboratories.
<ul>
              <li>The ToolKit contains experimental data, both published and unpublished, so not all experiments will connect to a publication.</li>

    <li>The ToolKit contains the tools (model systems, guides, delivery systems, genome editors, vectors, and protocols) used in creating the experimental data.</li>
</ul>
            </div>

        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    2. Where does the data come from?
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                Data comes from the NIH Common Fund SCGE consortium projects which can include both published and unpublished data.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingThree">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    3. Can anyone contribute data to the ToolKit?
                </button>
            </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
                No. Only projects supported by the NIH Common Fund SCGE Consortium can submit data.             </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading4">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
                    4. How is the website organized?
                </button>
            </h5>
        </div>
        <div id="collapse4" class="collapse" aria-labelledby="heading4" data-parent="#accordion">
            <div class="card-body">
                The top level is "Projects".Each Project has a one-to-one relationship with a NIH grant . The grant specifies what experiments the lab will conduct.


                Each project contains one or more experiments. You can view a list of all the <a href="/toolkit/data/search/results/Project">"Projects"</a>


                As labs complete experiments they submit the data and information about the associated tools (model systems, genome editors, delivery systems, vectors, guides, protocols) to the SCGE ToolKit team.


                The page for each "experiment" shows the data in several forms (as graphs if appropriate for the data and in a table). Experimental data can be downloaded as a .CSV file. Other files submitted along with the data can also be downloaded. You can view a list of all the <a href="/toolkit/data/search/results/Experiment">"experiments" (link)</a>&nbsp;or from the main menu


                Each tool has its own descriptive page along with links to other experiments that used the same tool.           </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading5">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse5" aria-expanded="false" aria-controls="collapse5">
                    5. What is the purpose of the SCGE ToolKit?
                </button>
            </h5>
        </div>
        <div id="collapse5" class="collapse" aria-labelledby="heading5" data-parent="#accordion">
            <div class="card-body">
                To provide access to SCGE consortium generated data to the broader biomedical research community in order to advance genome editing technologies to the clinic.             </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header" id="heading6">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse6" aria-expanded="false" aria-controls="collapse6">
                    6. Is the repository complete or will more experiments be added?
                </button>
            </h5>
        </div>
        <div id="collapse6" class="collapse" aria-labelledby="heading6" data-parent="#accordion">
            <div class="card-body">
                Data continue to be submitted by SCGE funded projects through December 2024. Some limited data may become available after this date.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading7">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse7" aria-expanded="false" aria-controls="collapse7">
                    7. I want to see everything the site has about a particular organ – how do I do that?
                </button>
            </h5>
        </div>
        <div id="collapse7" class="collapse" aria-labelledby="heading7" data-parent="#accordion">
            <div class="card-body">
                Use the search box at the top of the site.

            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading8">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse8" aria-expanded="false" aria-controls="collapse8">
                    8. I don’t see a publication listed with the experiment I viewed, where is it?
                </button>
            </h5>
        </div>
        <div id="collapse8" class="collapse" aria-labelledby="heading8" data-parent="#accordion">
            <div class="card-body">
                <div>Experiments may be unpublished and therefore not associated with a publication at the time of submission to the ToolKit.
                When an experiment is associated with a publication there is a link in the summary section on that experiment’s page.
                </div><br>
                <img src="/toolkit/common/images/faqs/publicationLinkHelp.png" alt="faq-help" style="width: 100%"/>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading9">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse9" aria-expanded="false" aria-controls="collapse9">
                    9. Will you eventually add more model systems?
                </button>
            </h5>
        </div>
        <div id="collapse9" class="collapse" aria-labelledby="heading9" data-parent="#accordion">
            <div class="card-body">
                Data are being submitted and processed through December 2024. Some limited data may become available after this date.             </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading10">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse10" aria-expanded="false" aria-controls="collapse10">
                    10. The reagent/sample names (e.g., ABE7.10, 113-012B) are unfamiliar, where did they come from?
                </button>
            </h5>
        </div>
        <div id="collapse10" class="collapse" aria-labelledby="heading10" data-parent="#accordion">
            <div class="card-body">
                Individual labs name their reagents and pass along those names when submitting their data. Clicking on a tool name will give you more information about the tool.             </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading11">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse11" aria-expanded="false" aria-controls="collapse11">
                    11. Can I use data from SCGE ToolKit in a publication of my own?
                </button>
            </h5>
        </div>
        <div id="collapse11" class="collapse" aria-labelledby="heading11" data-parent="#accordion">
            <div class="card-body">
                Yes. See the <a href="/toolkit/data/citation">Citing the ToolKit</a> page.

                If you download data for an experiment the .csv file will have citing instructions in the top row of the file.
            </div>
    </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading12">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse12" aria-expanded="false" aria-controls="collapse12">
                    12. How do I cite data from the SCGE ToolKit?
                </button>
            </h5>
        </div>
        <div id="collapse12" class="collapse" aria-labelledby="heading12" data-parent="#accordion">
            <div class="card-body">
                See the <a href="/toolkit/data/citation">Citing the ToolKit</a> page.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading13">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse13" aria-expanded="false" aria-controls="collapse13">
                    13. Why do some experiments have images and others don’t?
                </button>
            </h5>
        </div>
        <div id="collapse13" class="collapse" aria-labelledby="heading13" data-parent="#accordion">
            <div class="card-body">
                <div>
                The labs determine what files to submit along with their experimental data. From each experiment’s page you can view a list of the Submitted Files and download the ones of interest to you.
                </div><br><img src="/toolkit/common/images/faqs/submittedFileLinkHelp.png" alt="Submitted Files Link" style="width: 100%;"/>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading14">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse14" aria-expanded="false" aria-controls="collapse14">
                    14. Does the repository contain both target and off-target data?
                </button>
            </h5>
        </div>
        <div id="collapse14" class="collapse" aria-labelledby="heading14" data-parent="#accordion">
            <div class="card-body">
                Some experiments have both target and off-target data.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading15">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse15" aria-expanded="false" aria-controls="collapse15">
                    15. Why do some experiments not indicate what tissue was the target?
                </button>
            </h5>
        </div>
        <div id="collapse15" class="collapse" aria-labelledby="heading15" data-parent="#accordion">
            <div class="card-body">
                The submitting laboratory did not specify the target tissue when submitting the experiment data.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading16">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse16" aria-expanded="false" aria-controls="collapse16">
                    16. Where can I find the protocol for an experiment?
                </button>
            </h5>
        </div>
        <div id="collapse16" class="collapse" aria-labelledby="heading16" data-parent="#accordion">
            <div class="card-body">
                <div>
                    Not all labs submit the protocols for their experiment. If a lab has submitted a protocol for an experiment, you can find it under the Submitted Files link in the summary area at the top of the experiment’s page.
                </div><br><div>
                <img src="/toolkit/common/images/faqs/submittedFileLinkHelp.png" alt="Submitted Files Link" style="width: 100%;"/>
            </div>
                <br>
                You can also see a list of all the <a href="/toolkit/data/search/results/Protocol">Protocols</a> available on the site.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading17">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse17" aria-expanded="false" aria-controls="collapse17">
                    17. What data is available for an experiment?
                </button>
            </h5>
        </div>
        <div id="collapse17" class="collapse" aria-labelledby="heading17" data-parent="#accordion">
            <div class="card-body">
                <div>
                    Available data could include:
                    <ul>
                        <li>Raw data as submitted by the investigators.</li>
                        <li>Curated and processed data is integrated into the Toolkit and available for download.<br>
                            - On each "experiments" page, you can download all, or a subset of the experiment’s data</li>
                        <li>Additional files submitted by the lab such as images, presentation slide decks, protocols, etc. <br>
                            On each experiment’s page you can access those additional files. Look for a Submitted Files link in the summary area at the top of the experiment’s page.</li>
                    </ul>
                   </div>
                <br>
                <div>
                <img src="/toolkit/common/images/faqs/submittedFileLinkHelp.png" alt="Submitted Files Link" style="width: 100%;"/>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading18">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse18" aria-expanded="false" aria-controls="collapse18">
                    18. If an experiment has been replicated by a follow-up experiment, where can I see those results?
                </button>
            </h5>
        </div>
        <div id="collapse18" class="collapse" aria-labelledby="heading18" data-parent="#accordion">
            <div class="card-body">
                <div>
                    If an experiment has been validated, a link to the validation experiment will be listed in the summary area for the experiment
                </div>
                <br>
                <div>
                <img src="/toolkit/common/images/faqs/validationResultsLinkHelp.png" alt="Submitted Files Link" style="width: 100%;"/>
                </div>
                <br>
                <div>
                Validation experiments provide a link to the original experiment in the summary section
                </div>
                <br>
                <img src="/toolkit/common/images/faqs/originalExperimentLinkHelp.png" alt="Submitted Files Link" style="width: 100%;"/>

            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading19">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse19" aria-expanded="false" aria-controls="collapse19">
                    19. If a guide was used in multiple experiments, was it the same sequence?
                </button>
            </h5>
        </div>
        <div id="collapse19" class="collapse" aria-labelledby="heading19" data-parent="#accordion">
            <div class="card-body">
                If you click on the guide name it will take you to the guide details page and lists other aliases.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading20">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse20" aria-expanded="false" aria-controls="collapse20">
                    20. Can I see what other experiments have used a particular tool?
                </button>
            </h5>
        </div>
        <div id="collapse20" class="collapse" aria-labelledby="heading20" data-parent="#accordion">
            <div class="card-body">
                On the details page of the particular tool of interest, all submitted experiments that have used this exact tool will be listed.             </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading21">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse21" aria-expanded="false" aria-controls="collapse21">
                    21. How can I order a reagent I found on this site?
                </button>
            </h5>
        </div>
        <div id="collapse21" class="collapse" aria-labelledby="heading21" data-parent="#accordion">
            <div class="card-body">
                If that information was provided during the submission it will be listed on the tool details page.  If no information is provided, we suggest that you reach out to the Principal Investigator for the project.

            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="heading22">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse22" aria-expanded="false" aria-controls="collapse22">
                    22. How can I order a model system I found on this site?
                </button>
            </h5>
        </div>
        <div id="collapse22" class="collapse" aria-labelledby="heading22" data-parent="#accordion">
            <div class="card-body">
                No models are available through the ToolKit. Please contact the submitters for more information.
            </div>
        </div>
    </div>
</div>
</div>