<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page import="edu.mcw.scge.dao.spring.CountQuery" %>
<%@ page import="edu.mcw.scge.dao.implementation.StatsDao" %><%--
  Created by IntelliJ IDEA.
  User: jthota
  Date: 5/8/2020
  Time: 2:05 PM
  To change this template use File | Settings | File Templates.
--%>

<% StatsDao sdao = new StatsDao(); %>
<style>
    .card-label {
        font-weight: bold;
        border: 0;
        color: #017dc4;
        font-size:20px;
        padding-left:20px;
    }
    .card-image {
        height:80px;
        width:80px;
    }
    .card-body {
        padding: 0.25rem;
    }
    .card {
        border:0px solid black;
    }
    .circle-icon {
        background: #34cceb;
        padding:15px;
        border-radius: 50%;
    }
</style>

<div class="container" align="center">
<table align="center" >
    <tr>
        <td colspan="2">
            <b style="color:black;font-size:24px;font-family: 'Roboto', sans-serif;">What you need to know about the SCGE Toolkit</b>
        </td>
        <tr>
            <td valign="top"><img src="/toolkit/images/bullet_30.png" style="padding-left:25px;padding-right:10px;"/></td>
            <td style="padding-bottom:5px;font-size:16px;font-family: 'Roboto', sans-serif;">We make data generated by participating laboratories across <a href="/toolkit/data/initiatives"><span style="font-weight:700;">five consortium initiatives</span></a> publicly accessible</td>
        </tr>
    <tr>
        <td valign="top"><img src="/toolkit/images/bullet_30.png?" style="padding-left:25px;padding-right:10px;"/></td>
        <td style="padding-bottom:5px;font-size:16px;font-family: 'Roboto', sans-serif;">We provide <a href="/toolkit/data/search/results/Experiment?searchTerm="><span style="font-weight:700;">published and unpublished</span></a> data for the community to explore and build upon</td>
    </tr>
    <tr>
        <td valign="top"><img src="/toolkit/images/bullet_30.png" style="padding-left:25px;padding-right:10px;"/></td>
        <td style="padding-bottom:5px;font-size:16px;font-family: 'Roboto', sans-serif;">We showcase development and <a href="/toolkit/data/search/results/Experiment?searchTerm=&facetSearch=true&unchecked=&selectedFiltersJson=%7B%7D&initiative=Small+Animal+Testing+Center+%28SATC%29"><span style="font-weight:700;">independent validation of novel delivery systems</span></a> using unique preclinical model systems</td>
    </tr>
    <tr>
        <td valign="top"><img src="/toolkit/images/bullet_30.png" style="padding-left:25px;padding-right:10px;"/></td>
        <td style="padding-bottom:5px;font-size:16px;font-family: 'Roboto', sans-serif;">We include studies on the <a href="/toolkit/data/search/results/Experiment?searchTerm=&facetSearch=true&initiative=Biological+Systems"><span style="font-weight:700;">intended and unintended biological effects</span></a> of gene editing</td>
    </tr>
        <tr>
            <td colspan="2">
                <a target="_blank" href="https://scge.mcw.edu" title="Go to SCGE Main Site"><button class="btn btn-primary btn-sm" style="margin-top:20px;margin-bottom:15px;margin-left:25px;">Learn more about the SCGE program</button></a>
            </td>
        </tr>
</table>
</div>
<hr>

<div class="row" style="width:1000px;margin:auto;padding-top:15px;">
    <div class="col-sm-4" style="border-right: 1px solid #E5E5E5;">

        <!---   studies by initiative card -->

        <div class="card" >
            <div class="card-body" >
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Experiment?searchTerm=">
                            <table border="0">
                                <tr>
                                    <td><img src="/toolkit/images/studies.png" class="card-image" alt=""/></td>
                                    <td class="card-label">
                                        Explore Data
                                    </td>
                                </tr>
                            </table>


                        </a>
                    </li>
                </ul>
            </div>
        </div>

<!--
        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/publications/search">
                            <table>
                                <tr>
                                    <td>
                                        <img src="/toolkit/images/publication.png"  class="card-image"  alt=""/>
                                    </td>
                                    <td class="card-label">
                                        Publications
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        -->

        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/initiatives">
                            <table>
                                <tr>
                                    <td>
                                        <img src="/toolkit/images/initiative.png"  class="card-image"  alt=""/>
                                    </td>
                                    <td class="card-label">
                                        About&nbsp;SCGE
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Project?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                                        <div class="rounded" ><i class="fa-solid fa-diagram-project fa-3x circle-icon" ></i></div>
                                    </td>
                                    <td class="card-label">
                                      Explore Projects
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div> <!--close col -->

    <div class="col-sm-4">


        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Genome%20Editor?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                                        <img src="/toolkit/images/Editor-rev.png"  class="card-image" alt=""/>
                                    </td>
                                    <td class="card-label">
                                        Genome&nbsp;Editors
                                    </td>
                                </tr>
                                </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Model%20System?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                                        <img src="/toolkit/images/mouse.png"  class="card-image" alt=""/>

                                    </td>
                                    <td class="card-label">
                                        Model&nbsp;Systems
                                    </td>
                                </tr>
                            </table>

                        </a>
                    </li>
                </ul>
            </div>
        </div>


        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Delivery%20System?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                            <img src="/toolkit/images/Delivery.png"  class="card-image"  alt=""/>
                                    </td>
                                    <td class="card-label" >
                                        Delivery&nbsp;Systems
                                    </td>
                                </tr>
                                </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div> <!--close col -->
    <div class="col-sm-4" >


        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Guide?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                            <img src="/toolkit/images/guide.png"   class="card-image" alt=""/>
                                    </td>
                                    <td class="card-label">
                                        Guides
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>


        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/search/results/Vector?searchTerm=">
                            <table>
                                <tr>
                                    <td>
                            <img src="/toolkit/images/vector.png"  class="card-image"  alt=""/>
                                    </td>
                                    <td class="card-label">
                                        Vectors
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>


        <div class="card">
            <div class="card-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="/toolkit/data/protocols/search">
                            <table>
                                <tr>
                                    <td>
                            <img src="/toolkit/images/protocols.png"  class="card-image"  alt=""/>
                                    </td>
                                    <td class="card-label">
                                        Protocols
                                    </td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- end studies by initiative card -->
    </div>
</div>



<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>