<%@ page import="edu.mcw.scge.datamodel.Person" %>
<%@ page import="edu.mcw.scge.configuration.Access" %>
<%@ page import="edu.mcw.scge.dao.implementation.PersonDao" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-150985023-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-150985023-1');
    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <% String seoDescription = (String) request.getAttribute("seoDescription");
        String seoTitle = (String) request.getAttribute("seoTitle");
        if (seoDescription == null) {
            seoDescription="Database of study and experiment data generated by the Somatic Cell Genome Editing Consortium";
        }
        if (seoTitle == null) {
            seoTitle="Somatic Cell Genome Editing Consortium";
        }

        seoTitle += " | SCGE Toolkit";

    %>

    <meta name="description" content="<%=seoDescription%>">
    <meta name="author" content="Somatic Cell Genome Editing Consortium">
    <title><%=seoTitle%>></title>

    <!--
    <link rel='dns-prefetch' href='//s.w.org' />
    <link rel="alternate" type="application/rss+xml" title="Somatic Cell Gene Editing &raquo; Feed" href="https://scge.mcw.edu/feed/" />
    <link rel="alternate" type="application/rss+xml" title="Somatic Cell Gene Editing &raquo; Comments Feed" href="https://scge.mcw.edu/comments/feed/" />
    <link rel="alternate" type="text/calendar" title="Somatic Cell Gene Editing &raquo; iCal Feed" href="https://scge.mcw.edu/events/?ical=1" />
-->
    <meta property="og:title" content="<%=seoTitle%>"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="https://scge.mcw.edu/"/>
    <meta property="og:site_name" content="Somatic Cell Gene Editing Toolkit"/>
    <meta property="og:description" content="<%=seoDescription%>"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    <!--link href="css/dashboard.css" rel="stylesheet"-->
    <link href="/toolkit/common/tableSorter/css/filter.formatter.css" rel="stylesheet" type="text/css"/>
    <link href="/toolkit/common/tableSorter/css/theme.jui.css" rel="stylesheet" type="text/css"/>
    <link href="/toolkit/common/tableSorter/css/theme.blue.css" rel="stylesheet" type="text/css"/>

    <script src="/toolkit/common/tableSorter/js/tablesorter.js"> </script>
    <script src="/toolkit/common/tableSorter/js/jquery.tablesorter.widgets.js"></script>
    <!--link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/-->

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet" type="text/css"/>

    <link href="/toolkit/css/scge.css" rel="stylesheet" type="text/css"/>
    <link href="/toolkit/css/base.css" rel="stylesheet" type="text/css"/>


    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!--script src="https://code.jquery.com/jquery-1.12.4.js"></script-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">
    <link href="/toolkit/css/caret.css" rel="stylesheet" type="text/css"/>
    <script src="/toolkit/js/scge.js"></script>
</head>

<body>
<%@include file="feedbackForm.jsp"%>

<%

    Access access = new Access();
    Person person = access.getUser(request.getSession());

%>
<div id="site-wrapper" style="position:relative; left:0px; top:00px;">
    <div id="devSystemWarning" style="display:none; font-size:12px; color:white; background-color: #770C0E; width:100%;padding-left:15px;padding-top:4px; padding-bottom:4px;">Development System<br><%=seoTitle%><br><%=seoDescription%></div>

    <div style="font-size:12px; color:white; background-color: black; width:100%;padding-left:15px;padding-top:4px; padding-bottom:2px;">
        <div style="text-align:right; color:white;padding-right:12px;">
            <a href="https://scge.mcw.edu" style="color:white;">SCGE Consortium Home</a>&nbsp;&nbsp;
            |&nbsp;&nbsp;<a style="color:white;" href="/toolkit/data/initiatives">About SCGE</a>&nbsp;&nbsp;
            |&nbsp;&nbsp;<a style="color:white;" onclick="openForm()" href="javascript:void(0)">Contact Us</a>&nbsp;&nbsp;
            |&nbsp;&nbsp;<a style="color:white;" href="/toolkit/data/citation">Citing the Toolkit</a>&nbsp;&nbsp;
            |&nbsp;&nbsp;<a style="color:white;" href="https://creativecommons.org/licenses/by/4.0/">License</a>&nbsp;&nbsp;
        </div>
    </div>

    <script>
        if (location.href.indexOf("dev.") > 0 || location.href.indexOf("localhost") > 0) {
            document.getElementById("devSystemWarning").style.display="block";
        }
    </script>

    <%@include file="navbarTop.jsp"%>
    <%@include file="navbar.jsp"%>

    <div id="main">
        <% if (request.getAttribute("crumbtrail") != null) {%>
        <div class="container-fluid" style="padding-bottom: 2px;"><%=request.getAttribute("crumbtrail")%></div>
        <%}%>

            <div class="" style="margin-top: 0;padding-top: 0">
                <div class="container-fluid">
                    <c:choose>
                        <c:when test="${action!=null}">
                            <h4 style=";padding-top:10px;">${action}  </h4>
                            <c:if test="${study!=null && ( study.multiplePis!=null)}">
                                <small><strong>PI:</strong>  &nbsp;
                                    <c:forEach items="${study.multiplePis}" var="pi">
                                      ${pi.name}&nbsp;
                                    </c:forEach>
                        <c:if test="${fn:length( publication.articleIds)>0}">
                        <span style="color:orange; font-weight: bold">Publication IDs:</span>
                        <c:forEach items="${publication.articleIds}" var="id">

                            <c:choose>
                                <c:when test="${id.url=='' || id.url==null}">
                                    ${id.id};&nbsp;

                                </c:when>
                                <c:otherwise>
                                    <a href="${id.url}${id.id}">${id.id}</a>;&nbsp;

                                </c:otherwise>
                            </c:choose>
                        </c:forEach>
                        </c:if>
                        <c:if test="${nihReporterLink!=null}">
                            <a href="${nihReporterLink}" target="_blank"><img src="/toolkit/images/nihReport.png" alt="NIH Report" > </a>
                        </c:if>
                    </small>

                                <c:if test="${fn:contains(action,'Experiment:' )}">
                                  <div style="margin-left: 40%">
                                      <div class="row">
                                          <div class="col-lg-push-2">
                                      <button style="margin-bottom:15px;" class="btn btn-primary btn-sm" type="button"
                                              onclick="javascript:location.href='/toolkit/data/experiments/group/${study.groupId}'">Parent Project Page
                                      </button>&nbsp;
                                          </div>
                                          <div class="col-lg-push-3">
                                              <c:if test="${fn:length(tissues)==0 || resultType!=null}">
                                              <button style="margin-bottom:15px;"  class="btn btn-primary btn-sm" type="button"
                                                      onclick="javascript:openModalDialog()">Show Help
                                              </button>&nbsp;
                                              </c:if>
                                          </div>
                                          <div class="col-lg-push-3">
                                <button style="margin-bottom:15px;" class="btn btn-primary btn-sm" type="button"
                                        onclick="javascript:location.href='/toolkit/download/${study.studyId}'"><i
                                        class='fas fa-download'></i>&nbsp;Download Submitted files
                                </button>
                                          </div>
                                      </div>
                        </div>
                                </c:if>
                    </c:if>
                        <c:if test="${projectDescription!=null}">
                            <div>
                                        <div class="card" style="border:transparent">
                                            <div >
                                                <b>Description:</b>&nbsp;${projectDescription}

                                            </div>
                                        </div>


                            </div>
                        </c:if>
                        <hr>
                            <c:if test="${action=='Dashboard'}">
                                <div align="right">
                                    <c:forEach items="${personInfoList}" var="i">
                                        <p style="padding: 0;" class="text-muted">
                                            <strong>Initiative:</strong> ${i.groupName} &nbsp;
                                            <strong>User Group:</strong> ${i.subGroupName}</p>
                                    </c:forEach>
                                </div>
                            </c:if>
                    <div style="margin-top: 0;padding-top:0">
                        <!--nav aria-label="breadcrumb" id="breadcrumb"></nav-->
                        <nav aria-label="breadcrumb" >

                                <c:if test="${crumbTrailMap!=null && (searchTerm!=null && searchTerm!='')}">
                                    <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/toolkit/loginSuccess?destination=base">Home</a></li>

                                    <c:forEach items="${crumbTrailMap}" var="item">
                                        <li class="breadcrumb-item">
                                            <c:forEach items="${item.value}" var="trail">
                                                <c:if test="${item.value!=null}">
                                                    <a href="${trail.value}">
                                                </c:if>
                                                ${trail.key}
                                                <c:if test="${item.value!=null}">
                                                    </a>
                                                </c:if>


                                            </c:forEach>
                                        </li>
                                    </c:forEach>
                                    </ol>
                                </c:if>
                                <!--li class="breadcrumb-item">${action}</li-->


                        </nav>

                        </c:when>
                        <c:otherwise>
                            <form id="searchFormBasePage" action="/toolkit/data/search/results" >
                        <div class="container-fluid  jumbotron"  id="home-page-search" style="background-color: #FFFFFF;padding-top: 20px;padding-bottom: 20px">
                            <div>
                                <div class="row d-flex justify-content-center" align="center">
                                    <div class="col-lg-1" style="padding-top:0;">
                                        <!--td><img src="/toolkit/images/scge-logo-200w.png" border="0"/></td-->
                                        <img src="/toolkit/images/scge-logo-200w.png" width="150" style="padding-top: 0;margin-top: 0" alt="SCGE"/>
                                    </div>
                                    <div class="col-lg-6" style="padding-top: 22px;padding-left:5%">
                                        <div class="input-group md-form form-sm form-2 pl-0">
                                            <input class="form-control my-0 py-1 amber-border" id="searchTerm" name="searchTerm" type="text" placeholder="Search SCGE Toolkit" aria-label="Search">
                                            <div class="input-group-append">
                                             <span class="input-group-text amber lighten-3 btn" id="basic-text1" onclick="$('#searchFormBasePage').submit()"><i class="fas fa-search text-grey"
                                                                                   aria-hidden="true"></i></span>
                                            </div>
                                        </div>
                                        <small class="form-text text-muted" style="font-size: 11px">Examples: <a href="/toolkit/data/search/results?searchTerm=Epithelium">Epithelium</a>, <a href="/toolkit/data/search/results?searchTerm=CRISPR" >CRISPR</a>,
                                            <a href="/toolkit/data/search/results?searchTerm=AAV" >AAV</a>, <a href="/toolkit/data/search/results?searchTerm=Ai9" >Ai9</a>
                                        </small>
                                    </div>

                                </div>
                            </div>
                        </div>
                            </form>

                        </c:otherwise>
                    </c:choose>
                        <c:if test="${status!=null}">
                           <strong>${status}</strong><hr>
                        </c:if>
                        <c:if test="${page!=null}">
                        <c:import url="${page}.jsp" />
                        </c:if>
                    </div>
                </div>
            </div>

    </div>
</div>


<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
        <a  onclick="openForm()" href="javascript:void(0)" style="font-weight: 400;font-size: 16px;color:#FFFFFF"><i class="fa fa-phone" aria-hidden="true"></i>Contact Us</a>&nbsp;
        &nbsp;|&nbsp;
        <a href="https://creativecommons.org/licenses/by/4.0/" style=";color:#FFFFFF">License CC BY 4.0</a>&nbsp;&nbsp;&nbsp;<br>
        <small>Copyright &copy; This website is hosted by the SCGE DCC | Copyright 2022 SCGE | All Rights Reserved</small>
    </div>
    <script src="/toolkit/js/search/autocomplete.js"></script>

</footer>


</body>
</html>
